name: CI
on:
  schedule:
    - cron: "0 0 1 * *" # Run every month
  # This way, we can make sure code doesn't break via external dependencies
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
          - "3.12"
          - |
            3.8
            3.9
            3.10
            3.11
            3.12
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: echo "${{ matrix.python-version }}" > .python-version
      - name: Install dependencies
        run: uv sync
      - name: Run test suite
        run: uv run pytest -vvv --cov=idae --cov-report=xml
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build project
        run: uv build
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Run style lints
        run: |
          uv run black idae --check
          uv run ruff check idae --select I
      - name: Run ruff lints
        run: uv run ruff check idae
      - name: Run mypy lints
        run: uv run mypy idae --strict
